-- ===================================================================
-- ARQUIVO X-BR — O hoax do Grand Canyon de 1909
-- Rode isto no SQL Editor do Supabase (depois de seed-criptopaleontologia.sql).
-- ===================================================================

insert into ufologia.criptopaleontologia
  (titulo, slug, categoria, periodo, descricao, teoria_conspiracao, ordem, publicado)
values

('O hoax do Grand Canyon de 1909', 'hoax-grand-canyon-1909', 'Fraude documentada', '1909; desmentido segue sendo repetido até hoje',
 'Em 5 de abril de 1909, o jornal Arizona Gazette publicou uma matéria de capa alegando que um explorador chamado G. E. Kincaid, financiado pelo Smithsonian e liderado por um "professor S. A. Jordan", havia descoberto uma cidade subterrânea entalhada na rocha do Grand Canyon — com múmias, hieróglifos, ídolos e artefatos de suposta origem egípcia ou oriental, abrigando até 50 mil pessoas. Nenhum outro jornal da época replicou a história (o que já era estranho pros padrões de sensacionalismo jornalístico de 1909), nenhuma fotografia jamais apareceu, e o Smithsonian nunca teve registro de nenhum dos dois homens. Pesquisadores como Jason Colavito rastrearam a matéria como invenção quase certa do próprio jornal — prática comum na imprensa amarela da época. Curiosamente, o próprio Clarence Dutton, geólogo do United States Geological Survey, já vinha batizando formações do Grand Canyon com nomes de divindades egípcias e hindus desde 1882 — Vishnu Temple, Shiva Temple, Isis Temple, Osiris Temple, Tower of Ra — nomes que continuam oficialmente nos mapas do parque até hoje, simplesmente porque a escala das formações lembrava arquitetura religiosa monumental ao geólogo. Não é evidência de nada — é só a origem de uma coincidência de vocabulário que o hoax de 1909 aproveitou.',
 'O hoax de 1909 costuma ser citado, junto com a "conspiração do Smithsonian" sobre gigantes já catalogada aqui, como prova de que a instituição esconde arqueologia inconveniente. A negativa oficial do Smithsonian é tecnicamente verdadeira (não há registro de Kincaid nem de Jordan), mas ganhou um contexto real e preocupante em 2023: uma investigação do Washington Post revelou que o Smithsonian acumulou, ao longo do século XX, uma das maiores coleções de restos humanos do mundo — mais de 30 mil indivíduos, a maioria nativos americanos, boa parte coletada sem consentimento e com documentação tão precária que a própria instituição hoje admite não conseguir reconstituir a proveniência de parte do acervo (a coleção começou sob o curador Aleš Hrdlička, a partir de 1903). Isso não prova nenhuma cidade subterrânea egípcia — mas explica, com base documentada, por que a desconfiança institucional em torno desse período específico não é inteiramente irracional, mesmo quando o caso específico (o hoax de 1909) é, com alta confiança, ficção jornalística.',
 36, true);
